# Generated by Django 5.0.4 on 2024-04-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='опыт')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='сфера')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
